name: Image

on:
  workflow_call:

jobs:
  publish-docker-image:
    name: Build & Publish Docker Image
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.ref_name == 'main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          context: .
          push: ${{ github.ref_name == 'main' }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/syn-ack:latest
            ghcr.io/${{ env.OWNER_LC }}/syn-ack:${{ github.sha }}
